name: 修正依頼
description: ロゴの修正依頼
title: "[Fix] "
labels: ["fix"]
assignees:
  - SAWARATSUKI
body:
  - type: markdown
    attributes:
      value: |
        issuesに投稿してください。確認次第作成します。
        個人のスケジュールにより対応できない場合もあります。数日かかる場合もあります。
        ロゴは誤字脱字等の誤り修正のみ対応します。ロゴのデザイン変更は対応しません。

  - type: checkboxes
    id: duplicate-check
    attributes:
      label: 重複チェック
      description: 他のIssueと内容が重複していないことを確認してください。
      options:
        - label: 確認しました
          required: true

  - type: input
    id: service-name
    attributes:
      label: サービス名
      description: 修正を希望するサービスの名称
      placeholder: 例) GitHub
    validations:
      required: true

  - type: input
    id: revision-detail
    attributes:
      label: 修正内容
      description: 修正内容を具体的に記載してください
      placeholder: 例) Githubの日本語表記を「ぎっとはぶ」から「ギットハブ」に修正
    validations:
      required: true

  - type: textarea
    id: comment
    attributes:
      label: コメント・補足
      description: 修正する根拠がある場合はこちらに記載してください
    validations:
      required: false
