name: Request
description: Request a logo that's not here.
title: "[Request] "
labels: ["request", "enhancement"]
assignees:
  - SAWARATSUKI
body:
  - type: markdown
    attributes:
      value: |
        Please post it in the issues. We'll create it once confirmed.
        Depending on individual schedules, we may not be able to respond immediately. It may take several days.

  - type: checkboxes
    id: duplicate-check
    attributes:
      label: Check for duplicates
      description: Check that the Issue has not been duplicated.
      options:
        - label: Checked
          required: true

  - type: input
    id: service-name
    attributes:
      label: Service Name
      description: Name of service for which you would like to add a logo.
      placeholder: ex. GitHub
    validations:
      required: true

  - type: input
    id: service-name-ja
    attributes:
      label: Service name in Japanese
      description: How to read the service you wish to add in Japanese.
      placeholder: 例) ギットハブ
    validations:
      required: true

  - type: textarea
    id: comment
    attributes:
      label: Comment
      description: Please attach images to this area.
    validations:
      required: false
